<a href="https://colab.research.google.com/github/alihaider-ml/Deep_Learning_For_Computer_Vision/blob/main/Deep_Learning_for_Computer_vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of Tensors


## Initialization

In [2]:
import tensorflow as tf

In [ ]:
# constant is a method used for creating tensors
#zero dimensional tensor
tensor_zero_d = tf.constant(5)
print(tensor_zero_d)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
#one dimesional tenosr
tensor_one_d = tf.constant([1,2,3,-4])
print(tensor_one_d)

tf.Tensor([ 1  2  3 -4], shape=(4,), dtype=int32)


In [ ]:
#two dimensional tensor
tensor_two_d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
#three dimesional tensor
tensor_three_d = tf.constant([[[1,2,3],
                                [4,5,6],
                                [6,7,8]]])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [6 7 8]]], shape=(1, 3, 3), dtype=int32)


In [ ]:
#three dimesional tensor
tensor_three_d = tf.constant([[[1,2,3],
                                [4,5,6],
                                 [6,7,8]],
                              [[4,5,6],
                               [6,7,8],
                               [4,9,0]]])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [6 7 8]]

 [[4 5 6]
  [6 7 8]
  [4 9 0]]], shape=(2, 3, 3), dtype=int32)


In [ ]:
#four dimensional tensor
tensor_four_d = tf.constant([[[[1,2,3],
                               [4,5,6]],

                              [[8,9,0],
                              [2,5,7]]],


                             [[[6,7,8],
                             [6,3,4]],

                              [[1,2,3],
                               [4,5,6]]]])


print(tensor_four_d)
tensor_four_d.ndim

tf.Tensor(
[[[[1 2 3]
   [4 5 6]]

  [[8 9 0]
   [2 5 7]]]


 [[[6 7 8]
   [6 3 4]]

  [[1 2 3]
   [4 5 6]]]], shape=(2, 2, 2, 3), dtype=int32)


4

## Type Casting of Tensors

In [ ]:
#from float to integer
tensor_1d = tf.constant([1,2,3.,4], dtype=tf.float16)
casted_1d = tf.cast(tensor_1d,dtype = tf.int16)
print(tensor_1d)
print(casted_1d)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float16)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int16)


In [ ]:
#from integer to float
tensor_2d = tf.constant([[1,2,3],[45,6,6]],dtype=tf.int16)
casted_2d = tf.cast(tensor_2d,tf.float16)
print(tensor_2d)
print(casted_2d)

tf.Tensor(
[[ 1  2  3]
 [45  6  6]], shape=(2, 3), dtype=int16)
tf.Tensor(
[[ 1.  2.  3.]
 [45.  6.  6.]], shape=(2, 3), dtype=float16)


In [ ]:
# Note : we can also convert boolean to integers and integers to boolean 0 = false, any other number equal to true wheather negative or positive

## Converting numpy array to tensors

In [ ]:
import numpy as np

In [ ]:
np_array_1d = np.array([1,2,3,4])
converted_1d = tf.convert_to_tensor(np_array_1d)
print(np_array_1d)
print(converted_1d)

[1 2 3 4]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


## Methods in Tensorflow

In [ ]:
# Eye method : it is used to create identity matrix of needed shape
''' it's general syntax is like
    eye_tensor = tf.eye(
      num_of_row,
      num_of_columns,
      batch_shape, --> it defines the shape of the required identity matrix that how many matrices you want
      dtype,
      name
    ])
    '''

eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)


tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [ ]:
# eye tensor example
eye_tensor_2 = tf.eye(
          num_rows=4,
          num_columns=4,
          batch_shape=[4,3], #four dimension inside which three three matrix
          dtype=tf.dtypes.float16,
          name='Ali'
)
print(eye_tensor_2)

tf.Tensor(
[[[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]], shape=(4, 3, 4, 4), dtype=float16)


In [ ]:
# Fill method  : it creates a tensor filled with a scaler values
''' its general syntax is:
  tf.fill(
    dims,value,name
    ) '''

fill_tensor = tf.fill(
    [2,3],
    9,
    name='Ali'
)
print(fill_tensor)
float_fill_tensor = tf.cast(fill_tensor,dtype=tf.float16)
print(float_fill_tensor)


tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[9. 9. 9.]
 [9. 9. 9.]], shape=(2, 3), dtype=float16)


In [5]:
# Ones method : creates a tensor with all elements set to one
''' its general syntax is
    tf.ones (
      shape,
      dtype=tf.dtype.float32,
      name=None
    )
'''
ones_tensor = tf.ones(
    [2,3],
    dtype=tf.dtypes.float32,
      name=None
    )
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [8]:
# ones like : creates a tensor of all ones that has the same shape as inputs
''' it's general syntax is
    tf.ones_like(
      input,
      dtype=None,
      name=None
    )
'''


ones_like_tensor=tf.ones_like(
    [[1,2,3],[4,5,6]],
    dtype=tf.float32,
    name="Ali"
)


print(ones_like_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [13]:
# zeros method : creates a tensor with all the elements set to zero
''' it's general syntax is

    tf.zeros(
      shape,
      dtype=none,
      name=none
    )
  '''

zeros_tensor = tf.zeros(
      [3,4],
      dtype=tf.float32,
      name='Ali'
)

print(zeros_tensor)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [7]:
# shape : returns a tensor containing the shape of the input tensor
'''it's general syntax is

  tf.shape(
    input,
  )

'''

tensor_exp=tf.constant(
    [[1,2,3,3],[5,4,5,6]]
)

print(tf.shape(tensor_exp))

tf.Tensor([2 4], shape=(2,), dtype=int32)


In [5]:
# rank : returns rank of a tensor, actually it returns the shape of the number of starting brackets
''' it's general syntax is
    tf.rank(
      input,
      name=none
    )

'''

print(tf.rank(tensor_exp))

tf.Tensor(2, shape=(), dtype=int32)


In [8]:
# size : returns the size of the tensor, it actually returns the number of numbers in the tensors
''' it's general syntax is
    tf.size(
      input,
      out_type=tf.dtypes.float32,
      name=None
    )
'''

print(tf.size(tensor_exp,out_type=tf.dtypes.float32))

tf.Tensor(8.0, shape=(), dtype=float32)


In [11]:
# random.normal : outputs random values from normal distribution
''' it's general syntax is
    tf.random.normal(
      shape,
      mean=0.0,
      stddev=1.0,
      dtype=tf.dtypes.float32,
      seed=None,
      name=None
    )


    -->  Higher the value of standard deviation the range of values to appear in the matrix will be high
'''

random_tensor=tf.random.normal(
    [2,3],
    mean=50,
    stddev=3,
    dtype=tf.dtypes.float32,
    seed=None, # if we set this argument to any constant number then it will produce the same random number as much as we run this code
    name=None
)

print(random_tensor)

tf.Tensor(
[[52.03656  52.774837 52.52314 ]
 [50.373238 46.91962  45.721928]], shape=(2, 3), dtype=float32)


In [17]:
# random.uniform : outputs random values from a uniform distribution
''' it's general syntax is
    tf.ranom.uniform(
      shape,
      minval=0,
      maxval=None, # by default it is considered as one
      dtype=tf.dtypes.float32,
      seed=None,
      name=None

    )
'''
uniform_random_tensor = tf.random.uniform(
    [3,4],
    minval=2,
    maxval=34,  # if we set it to None then by default it is considered as one
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(uniform_random_tensor)

tf.Tensor(
[[ 3  7  2 33]
 [ 7  4 15 15]
 [12 19 21 31]], shape=(3, 4), dtype=int32)


## Indexing

In [15]:
indexed_tensor = tf.constant([1,2,3,4,5,6,7,8,9,10,11])
print(indexed_tensor)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11], shape=(11,), dtype=int32)


In [17]:
# indexing of a 1-d tensor
# its syntax is like [start:end:steps]
print(indexed_tensor[5])
print(indexed_tensor[0:4])
print(indexed_tensor[1:4])
print(indexed_tensor[0:10:2])

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [28]:
# indexing of 2-d tensors
indexing_2d_tensors = tf.constant(
    [[1,2,3],
     [4,5,6]]
)

# its syntax is like [rows : columns]

print(indexing_2d_tensors [0:2 , 0:1])
print('\n')
print(indexing_2d_tensors [0:2 , 2:] , '\n')
print(indexing_2d_tensors [0:2, 1:2], '\n')
print(indexing_2d_tensors [0:1,0:3]) #in the ending the column or the row you mention minus one gets print

tf.Tensor(
[[1]
 [4]], shape=(2, 1), dtype=int32)


tf.Tensor(
[[3]
 [6]], shape=(2, 1), dtype=int32) 

tf.Tensor(
[[2]
 [5]], shape=(2, 1), dtype=int32) 

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
