<a href="https://colab.research.google.com/github/alihaider-ml/Deep_Learning_For_Computer_Vision/blob/main/Deep_Learning_for_Computer_vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of Tensors


## Initialization

In [1]:
import tensorflow as tf

In [2]:
# constant is a method used for creating tensors
#zero dimensional tensor
tensor_zero_d = tf.constant(5)
print(tensor_zero_d)

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
#one dimesional tenosr
tensor_one_d = tf.constant([1,2,3,-4])
print(tensor_one_d)

tf.Tensor([ 1  2  3 -4], shape=(4,), dtype=int32)


In [5]:
#two dimensional tensor
tensor_two_d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [6]:
#three dimesional tensor
tensor_three_d = tf.constant([[[1,2,3],
                                [4,5,6],
                                [6,7,8]]])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [6 7 8]]], shape=(1, 3, 3), dtype=int32)


In [9]:
#three dimesional tensor
tensor_three_d = tf.constant([[[1,2,3],
                                [4,5,6],
                                 [6,7,8]],
                              [[4,5,6],
                               [6,7,8],
                               [4,9,0]]])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [6 7 8]]

 [[4 5 6]
  [6 7 8]
  [4 9 0]]], shape=(2, 3, 3), dtype=int32)


In [12]:
#four dimensional tensor
tensor_four_d = tf.constant([[[[1,2,3],
                               [4,5,6]],

                              [[8,9,0],
                              [2,5,7]]],


                             [[[6,7,8],
                             [6,3,4]],

                              [[1,2,3],
                               [4,5,6]]]])


print(tensor_four_d)
tensor_four_d.ndim

tf.Tensor(
[[[[1 2 3]
   [4 5 6]]

  [[8 9 0]
   [2 5 7]]]


 [[[6 7 8]
   [6 3 4]]

  [[1 2 3]
   [4 5 6]]]], shape=(2, 2, 2, 3), dtype=int32)


4

## Type Casting of Tensors

In [13]:
#from float to integer
tensor_1d = tf.constant([1,2,3.,4], dtype=tf.float16)
casted_1d = tf.cast(tensor_1d,dtype = tf.int16)
print(tensor_1d)
print(casted_1d)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float16)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int16)


In [14]:
#from integer to float
tensor_2d = tf.constant([[1,2,3],[45,6,6]],dtype=tf.int16)
casted_2d = tf.cast(tensor_2d,tf.float16)
print(tensor_2d)
print(casted_2d)

tf.Tensor(
[[ 1  2  3]
 [45  6  6]], shape=(2, 3), dtype=int16)
tf.Tensor(
[[ 1.  2.  3.]
 [45.  6.  6.]], shape=(2, 3), dtype=float16)


In [ ]:
# Note : we can also convert boolean to integers and integers to boolean 0 = false, any other number equal to true wheather negative or positive

## Converting numpy array to tensors

In [15]:
import numpy as np

In [16]:
np_array_1d = np.array([1,2,3,4])
converted_1d = tf.convert_to_tensor(np_array_1d)
print(np_array_1d)
print(converted_1d)

[1 2 3 4]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


## Methods in Tensorflow

In [19]:
# Eye method : it is used to create identity matrix of needed shape
''' it's general syntax is like
    eye_tensor = tf.eye(
      num_of_row,
      num_of_columns,
      batch_shape, --> it defines the shape of the required identity matrix that how many matrices you want
      dtype,
      name
    ])
    '''

eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)


tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [30]:
# eye tensor example
eye_tensor_2 = tf.eye(
          num_rows=4,
          num_columns=4,
          batch_shape=[4,3], #four dimension inside which three three matrix
          dtype=tf.dtypes.float16,
          name='Ali'
)
print(eye_tensor_2)

tf.Tensor(
[[[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]], shape=(4, 3, 4, 4), dtype=float16)


In [38]:
# Fill method  : it creates a tensor filled with a scaler values
''' its general syntax is:
  tf.fill(
    dims,value,name
    ) '''

fill_tensor = tf.fill(
    [2,3],9,name='Ali'
)
print(fill_tensor)
float_fill_tensor = tf.cast(fill_tensor,dtype=tf.float16)
print(float_fill_tensor)


tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[9. 9. 9.]
 [9. 9. 9.]], shape=(2, 3), dtype=float16)
