<a href="https://colab.research.google.com/github/alihaider-ml/Deep_Learning_For_Computer_Vision/blob/main/Deep_Learning_for_Computer_vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of Tensors


## Initialization

In [3]:
import tensorflow as tf

In [ ]:
# constant is a method used for creating tensors
#zero dimensional tensor
tensor_zero_d = tf.constant(5)
print(tensor_zero_d)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
#one dimesional tenosr
tensor_one_d = tf.constant([1,2,3,-4])
print(tensor_one_d)

tf.Tensor([ 1  2  3 -4], shape=(4,), dtype=int32)


In [ ]:
#two dimensional tensor
tensor_two_d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
#three dimesional tensor
tensor_three_d = tf.constant([[[1,2,3],
                                [4,5,6],
                                [6,7,8]]])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [6 7 8]]], shape=(1, 3, 3), dtype=int32)


In [ ]:
#three dimesional tensor
tensor_three_d = tf.constant([[[1,2,3],
                                [4,5,6],
                                 [6,7,8]],
                              [[4,5,6],
                               [6,7,8],
                               [4,9,0]]])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [6 7 8]]

 [[4 5 6]
  [6 7 8]
  [4 9 0]]], shape=(2, 3, 3), dtype=int32)


In [ ]:
#four dimensional tensor
tensor_four_d = tf.constant([[[[1,2,3],
                               [4,5,6]],

                              [[8,9,0],
                              [2,5,7]]],


                             [[[6,7,8],
                             [6,3,4]],

                              [[1,2,3],
                               [4,5,6]]]])


print(tensor_four_d)
tensor_four_d.ndim

tf.Tensor(
[[[[1 2 3]
   [4 5 6]]

  [[8 9 0]
   [2 5 7]]]


 [[[6 7 8]
   [6 3 4]]

  [[1 2 3]
   [4 5 6]]]], shape=(2, 2, 2, 3), dtype=int32)


4

## Type Casting of Tensors

In [ ]:
#from float to integer
tensor_1d = tf.constant([1,2,3.,4], dtype=tf.float16)
casted_1d = tf.cast(tensor_1d,dtype = tf.int16)
print(tensor_1d)
print(casted_1d)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float16)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int16)


In [ ]:
#from integer to float
tensor_2d = tf.constant([[1,2,3],[45,6,6]],dtype=tf.int16)
casted_2d = tf.cast(tensor_2d,tf.float16)
print(tensor_2d)
print(casted_2d)

tf.Tensor(
[[ 1  2  3]
 [45  6  6]], shape=(2, 3), dtype=int16)
tf.Tensor(
[[ 1.  2.  3.]
 [45.  6.  6.]], shape=(2, 3), dtype=float16)


In [ ]:
# Note : we can also convert boolean to integers and integers to boolean 0 = false, any other number equal to true wheather negative or positive

## Converting numpy array to tensors

In [ ]:
import numpy as np

In [ ]:
np_array_1d = np.array([1,2,3,4])
converted_1d = tf.convert_to_tensor(np_array_1d)
print(np_array_1d)
print(converted_1d)

[1 2 3 4]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


## Methods in Tensorflow

In [ ]:
# Eye method : it is used to create identity matrix of needed shape
''' it's general syntax is like
    eye_tensor = tf.eye(
      num_of_row,
      num_of_columns,
      batch_shape, --> it defines the shape of the required identity matrix that how many matrices you want
      dtype,
      name
    ])
    '''

eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)


tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [ ]:
# eye tensor example
eye_tensor_2 = tf.eye(
          num_rows=4,
          num_columns=4,
          batch_shape=[4,3], #four dimension inside which three three matrix
          dtype=tf.dtypes.float16,
          name='Ali'
)
print(eye_tensor_2)

tf.Tensor(
[[[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]], shape=(4, 3, 4, 4), dtype=float16)


In [ ]:
# Fill method  : it creates a tensor filled with a scaler values
''' its general syntax is:
  tf.fill(
    dims,value,name
    ) '''

fill_tensor = tf.fill(
    [2,3],
    9,
    name='Ali'
)
print(fill_tensor)
float_fill_tensor = tf.cast(fill_tensor,dtype=tf.float16)
print(float_fill_tensor)


tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[9. 9. 9.]
 [9. 9. 9.]], shape=(2, 3), dtype=float16)


In [ ]:
# Ones method : creates a tensor with all elements set to one
''' its general syntax is
    tf.ones (
      shape,
      dtype=tf.dtype.float32,
      name=None
    )
'''
ones_tensor = tf.ones(
    [2,3],
    dtype=tf.dtypes.float32,
      name=None
    )
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [ ]:
# ones like : creates a tensor of all ones that has the same shape as inputs
''' it's general syntax is
    tf.ones_like(
      input,
      dtype=None,
      name=None
    )
'''


ones_like_tensor=tf.ones_like(
    [[1,2,3],[4,5,6]],
    dtype=tf.float32,
    name="Ali"
)


print(ones_like_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [ ]:
# zeros method : creates a tensor with all the elements set to zero
''' it's general syntax is

    tf.zeros(
      shape,
      dtype=none,
      name=none
    )
  '''

zeros_tensor = tf.zeros(
      [3,4],
      dtype=tf.float32,
      name='Ali'
)

print(zeros_tensor)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [ ]:
# shape : returns a tensor containing the shape of the input tensor
'''it's general syntax is

  tf.shape(
    input,
  )

'''

tensor_exp=tf.constant(
    [[1,2,3,3],[5,4,5,6]]
)

print(tf.shape(tensor_exp))

tf.Tensor([2 4], shape=(2,), dtype=int32)


In [ ]:
# rank : returns rank of a tensor, actually it returns the shape of the number of starting brackets
''' it's general syntax is
    tf.rank(
      input,
      name=none
    )

'''

print(tf.rank(tensor_exp))

tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
# size : returns the size of the tensor, it actually returns the number of numbers in the tensors
''' it's general syntax is
    tf.size(
      input,
      out_type=tf.dtypes.float32,
      name=None
    )
'''

print(tf.size(tensor_exp,out_type=tf.dtypes.float32))

tf.Tensor(8.0, shape=(), dtype=float32)


In [ ]:
# random.normal : outputs random values from normal distribution
''' it's general syntax is
    tf.random.normal(
      shape,
      mean=0.0,
      stddev=1.0,
      dtype=tf.dtypes.float32,
      seed=None,
      name=None
    )


    -->  Higher the value of standard deviation the range of values to appear in the matrix will be high
'''

random_tensor=tf.random.normal(
    [2,3],
    mean=50,
    stddev=3,
    dtype=tf.dtypes.float32,
    seed=None, # if we set this argument to any constant number then it will produce the same random number as much as we run this code
    name=None
)

print(random_tensor)

tf.Tensor(
[[52.03656  52.774837 52.52314 ]
 [50.373238 46.91962  45.721928]], shape=(2, 3), dtype=float32)


In [ ]:
# random.uniform : outputs random values from a uniform distribution
''' it's general syntax is
    tf.ranom.uniform(
      shape,
      minval=0,
      maxval=None, # by default it is considered as one
      dtype=tf.dtypes.float32,
      seed=None,
      name=None

    )
'''
uniform_random_tensor = tf.random.uniform(
    [3,4],
    minval=2,
    maxval=34,  # if we set it to None then by default it is considered as one
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(uniform_random_tensor)

tf.Tensor(
[[ 3  7  2 33]
 [ 7  4 15 15]
 [12 19 21 31]], shape=(3, 4), dtype=int32)


## Indexing

In [ ]:
indexed_tensor = tf.constant([1,2,3,4,5,6,7,8,9,10,11])
print(indexed_tensor)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11], shape=(11,), dtype=int32)


In [ ]:
# indexing of a 1-d tensor
# its syntax is like [start:end:steps]
print(indexed_tensor[5])
print(indexed_tensor[0:4])
print(indexed_tensor[1:4])
print(indexed_tensor[0:10:2])

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [ ]:
# indexing of 2-d tensors
indexing_2d_tensors = tf.constant(
    [[1,2,3],
     [4,5,6]]
)

# its syntax is like [rows : columns]

print(indexing_2d_tensors [0:2 , 0:1])
print('\n')
print(indexing_2d_tensors [0:2 , 2:] , '\n')
print(indexing_2d_tensors [0:2, 1:2], '\n')
print(indexing_2d_tensors [0:1,0:3], '\n') #in the ending the column or the row you mention minus one gets print
print(indexing_2d_tensors [1,0:3], '\n')   # we can also use a single number to represent the whole row or the whole column
print(indexing_2d_tensors [...,1:2]  , '\n') #the three dots are also used for selecting all the rows or all the columns

tf.Tensor(
[[1]
 [4]], shape=(2, 1), dtype=int32)


tf.Tensor(
[[3]
 [6]], shape=(2, 1), dtype=int32) 

tf.Tensor(
[[2]
 [5]], shape=(2, 1), dtype=int32) 

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32) 

tf.Tensor([4 5 6], shape=(3,), dtype=int32) 

tf.Tensor(
[[2]
 [5]], shape=(2, 1), dtype=int32) 



In [ ]:
# indexing of the three d tensors

indexed_3d_tensor = tf.constant(
                    [[[1,2,3],[4,5,6]],
                     [[7,8,9],[10,11,12]],
                     [[33,23,12],[99,23,45]]]
)
''' the syntax for indexing three d tensor is like
    [matrix_no, row_no, column_no]
'''


print(indexed_3d_tensor [1,:,:],'\n\n')
print(indexed_3d_tensor [2,0,0],'\n\n') # printing any specific element
print(indexed_3d_tensor [1,1,1:3],'\n\n')
print(indexed_3d_tensor [1:2,1,2])

tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 


tf.Tensor(33, shape=(), dtype=int32) 


tf.Tensor([11 12], shape=(2,), dtype=int32) 


tf.Tensor([12], shape=(1,), dtype=int32)


## Functions of Mathematics

In [ ]:
# Absolute functions : compute the absolute value of a tensor
''' it's general syntax is
    tf.math.abs (
      x, name=None
    )
'''

abs_tensor = tf.constant(
    [[1,-2,3],[-3,-5,5]]
)

print(tf.math.abs(abs_tensor))

tf.Tensor(
[[1 2 3]
 [3 5 5]], shape=(2, 3), dtype=int32)


In [ ]:
# Addition function : computes the sum of two tensor element by element
''' it's general syntax is
    tf.add(tensor_1, tensor_2)'''

ten_1=tf.constant([[1,2,3],[4,5,6]])
ten_2=tf.constant([[7,8,9],[10,11,12]])
print(tf.add(ten_1,ten_2))

# it is not necessary that the shapes of the two tensor should be same for addition they can be like one is tensor and the other is just 0-d tensor

tf.Tensor(
[[4 5 6]
 [7 8 9]], shape=(2, 3), dtype=int32)


In [ ]:
# Multipy function : computes the product of two tensors element by element
''' it's general syntax is
    tf.multiply(tensor_1, tensor_2)'''

ten_1=tf.constant([[1,2,3],[4,5,6]])
ten_2=tf.constant([[7,8,9],[10,11,12]])
print(tf.multiply(ten_1,ten_2),'\n\n')



# there is one other scenerio here
ten3=tf.constant([1,2,3,4])
ten4=tf.constant([[1],[2],[3]])
print(tf.multiply(ten3,ten4))

tf.Tensor(
[[ 7 16 27]
 [40 55 72]], shape=(2, 3), dtype=int32) 


tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [ ]:
# Subtract function : computes the Subtraction of two tensors element by element
''' it's general syntax is
    tf.subtract(tensor_1, tensor_2)'''

ten_1=tf.constant([[1,2,3],[4,5,6]])
ten_2=tf.constant([[7,8,9],[10,11,12]])
print(tf.subtract(ten_1,ten_2))

tf.Tensor(
[[-6 -6 -6]
 [-6 -6 -6]], shape=(2, 3), dtype=int32)


In [ ]:
# Divide_no_nan function : computes the quotient of two tensors element by element and if the answer is not defined it returns zero
''' it's general syntax is
    tf.math.divide_no_nan(tensor_1, tensor_2)'''

ten_1=tf.constant([[1,2,3],[4,5,6]])
ten_2=tf.constant([[7,8,0],[10,11,12]])
print(tf.math.divide_no_nan(ten_1,ten_2))

tf.Tensor(
[[0.14285714 0.25       0.        ]
 [0.4        0.45454545 0.5       ]], shape=(2, 3), dtype=float64)


In [ ]:
# Maximum function : compares the two tensors element wise and returns the element of high value
''' it's general syntax is
    tf.maximum(tensor_1, tensor_2)'''

ten_1=tf.constant([[1,2,3],[4,5,6]])
ten_2=tf.constant([[7,8,0],[10,11,12]])
print(tf.math.maximum(ten_1,ten_2))

tf.Tensor(
[[ 7  8  3]
 [10 11 12]], shape=(2, 3), dtype=int32)


In [ ]:
# Minimum function : compares the two tensors element wise and returns the element of lowest value
''' it's general syntax is
    tf.minimum(tensor_1, tensor_2)'''

ten_1=tf.constant([[1,2,3],[4,5,6]])
ten_2=tf.constant([[7,8,0],[10,11,12]])
print(tf.minimum(ten_1,ten_2))

tf.Tensor(
[[1 2 0]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# ArgMax function : Returns the position of the maximum value
''' it's general syntax is
    tf.argmax(tensor_1)'''

ten_1=tf.constant([1,2,3])
print(tf.math.argmax(ten_1),'\n\n')


''' In another scenerio it's general syntax is
    tf.argmax(tensor_1,axis=)
    Note : axis=0 means column wise and axis=1 means row wise
    each number represent the highest value in each  tensor'''


ten_1=tf.constant([[1,2,3],[4,5,6]])
print(tf.argmax(ten_1,1))

tf.Tensor(2, shape=(), dtype=int64) 


tf.Tensor([2 2], shape=(2,), dtype=int64)


In [ ]:
# ArgMin function : Returns the position of the minimum value
''' it's general syntax is
    tf.argmin(tensor_1)'''

ten_1=tf.constant([1,2,3])
print(tf.math.argmin(ten_1),'\n\n')


''' In another scenerio it's general syntax is
    tf.argmin(tensor_1,axis=)
    Note : axis=0 means column wise and axis=1 means row wise
    each number represent the lowest value in each  tensor'''


ten_1=tf.constant([[7,2,3],[4,5,6]])
print(tf.argmin(ten_1,0))

tf.Tensor(0, shape=(), dtype=int64) 


tf.Tensor([1 0 0], shape=(3,), dtype=int64)


In [ ]:
# Power method : It computes the power of one number in tensor to another
''' it's general syntax is
    tf.pow(x,y)
'''
tensor_1 = tf.constant(
                     [1,2,3,4]
)
tensor_2 = tf.constant(
                      [5,6,7,8]
)
print(tf.pow(tensor_1,tensor_2),'\n\n\n')





# for two dimensional tensors
tensor_3 = tf.constant([[1,2,3],[4,5,6]])
tensor_4 = tf.constant([[7,8,9],[10,11,12]])

print(tf.pow(tensor_4,tensor_3))

tf.Tensor([    1    64  2187 65536], shape=(4,), dtype=int32) 



tf.Tensor(
[[      7      64     729]
 [  10000  161051 2985984]], shape=(2, 3), dtype=int32)


In [ ]:
# Reduce sum Method : computes the sum of elements accross the dimensions of a tensor
''' It's general syntax is
    tf.reduce_sum(input_tensor, axis=0, keepdims=false, name=None)
'''


print(tf.reduce_sum(tensor_3, axis=None, keepdims=False, name=None), '\n\n\n') # if we don't mention the axis it will add up all the elements in the tensor
print(tf.reduce_sum(tensor_3, axis=0, keepdims=False, name=None), '\n\n\n') # column wise sum
print(tf.reduce_sum(tensor_3, axis=1, keepdims=False, name=None), '\n\n\n') # row wise sum



tf.Tensor(21, shape=(), dtype=int32) 



tf.Tensor([5 7 9], shape=(3,), dtype=int32) 



tf.Tensor([ 6 15], shape=(2,), dtype=int32) 





In [ ]:
# Reduce max Method : returns maximum of elements accross the dimensions of a tensor
''' It's general syntax is
    tf.reduce_max(input_tensor, axis=0, keepdims=false, name=None)
'''


print(tf.reduce_max(tensor_3, axis=None, keepdims=False, name=None), '\n\n\n') # if we don't mention the axis it will search up all the elements in the tensor and return maximum
print(tf.reduce_max(tensor_3, axis=0, keepdims=False, name=None), '\n\n\n') # column wise maximum
print(tf.reduce_max(tensor_3, axis=1, keepdims=False, name=None), '\n\n\n') # row wise maximum



tf.Tensor(6, shape=(), dtype=int32) 



tf.Tensor([4 5 6], shape=(3,), dtype=int32) 



tf.Tensor([3 6], shape=(2,), dtype=int32) 





In [ ]:
# Reduce mean Method : computes the mean of elements accross the dimensions of a tensor
''' It's general syntax is
    tf.reduce_mean(input_tensor, axis=0, keepdims=false, name=None)
'''


print(tf.reduce_mean(tensor_3, axis=None, keepdims=False, name=None), '\n\n\n') # if we don't mention the axis it will calculate the mean of all the elements in the tensor
print(tf.reduce_mean(tensor_3, axis=0, keepdims=False, name=None), '\n\n\n') # column wise mean
print(tf.reduce_mean(tensor_3, axis=1, keepdims=False, name=None), '\n\n\n') # row wise mean



tf.Tensor(3, shape=(), dtype=int32) 



tf.Tensor([2 3 4], shape=(3,), dtype=int32) 



tf.Tensor([2 5], shape=(2,), dtype=int32) 





In [ ]:
''' we have other functions which all work the same way like
    reduce_min()
    reduce_std()
    reduce_prod()
    reduce_variance()
    reduce_eucladian_norm()
'''

In [ ]:
# sigmoid function : computes the sigmoid of x element wise
''' it's general syntax is
    tf.sigmoid(x,name=None)

    mathematically --> sigmoid(x)=1/(1+exp(-x))
'''

print(tf.sigmoid(tf.constant([1,2,3],dtype=tf.float32)))

tf.Tensor([0.73105854 0.880797   0.95257413], shape=(3,), dtype=float32)


In [ ]:
# Top_k function : it will return the position of the top value from tensor
''' it's general syntax is
    tf.top_k(input, k=1, sorted=True, name=None)
'''

print(tf.math.top_k(tf.constant([1,9,2,3,8]),k=2, sorted=True)) # the argument k represents the number of top values to be returned

TopKV2(values=<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 8], dtype=int32)>, indices=<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>)


## Linear Algebra Operations

In [ ]:
# Matrix Multiplication : it does the real matrix multiplication
''' The general syntax for matrix multiplication is
    tf.linalg.matmul(
      a,b,transpose_a=false,transpose_b=false,adjoint_a=false,adjoint_b=false,
      a_is_sparse=false,b_is_sparse=false,output_type=none,name=None
    )

'''

a=tf.constant([[1,2,3],[4,5,6]])
b=tf.constant([[7,8],[4,9],[11,12]])
print(tf.linalg.matmul(
      a,b,transpose_a=False,transpose_b=False,adjoint_a=False,adjoint_b=False, # if we want to multiply matrix with trnspose of other then me set them to true
      a_is_sparse=False,b_is_sparse=False,output_type=None,name=None           # sparse tensor means the most element in the tensors are zero, so if we specify it we tell the compiler that a sparse tensor is coming so it takes care accordingly
      ))

print('\n\n\n')
# short cut for matrix multiplication
print(a@b)

tf.Tensor(
[[ 48  62]
 [114 149]], shape=(2, 2), dtype=int32)




tf.Tensor(
[[ 48  62]
 [114 149]], shape=(2, 2), dtype=int32)


In [ ]:
# Matrix Transpose : Rows are converted to columns and columns are converted to rows
print(tf.transpose(a))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [ ]:
# Matrix multiplication for 3-d tensors
import tensorflow as tf
mat_1=tf.constant(
                  [
                    [[1,2],
                    [3,4]],
                   [[5,6],
                    [7,8]]
                  ]
)

mat_2=tf.constant(
                  [[[2,5,4],
                    [6,9,2]],
                   [[7,4,1],
                    [6,9,9]]]
)

product_tensor=tf.linalg.matmul(mat_1,mat_2)
print(product_tensor)


''' The multiplication of matrices with more the two dimension are done batch wise mean the first batch in the matrix 1 is multiplied with the
  first batch of matrix 2 and so on'''

tf.Tensor(
[[[ 14  23   8]
  [ 30  51  20]]

 [[ 71  74  59]
  [ 97 100  79]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
# Band part method :
''' it's general syntax is
tf.linalg.band_part(input, num_lower, num_upper, name=None)
'''

print(tf.linalg.band_part(mat_1,0,0))

tf.Tensor(
[[[1 0]
  [0 4]]

 [[5 0]
  [0 8]]], shape=(2, 2, 2), dtype=int32)


In [ ]:
# Cholesky method : computes the cholesky decomposition of one or more square matrices
''' it's general syntax is
    tf.linalg.cholesky ( input, name=None)

    --> condition for it is the A = A^t then cholesky decomposition can be applied
    A = L*L^t

'''

tens_1=tf.constant([[3,4],[5,6]],dtype=tf.float32)
print(tf.linalg.cholesky(tens_1))

tf.Tensor(
[[nan  0.]
 [nan nan]], shape=(2, 2), dtype=float32)


In [ ]:
# Cross product : computes the pair wise cross product
''' it's general syntax is
    tf.linalg.cross(a,b,name=None)

'''
tens_1=tf.constant([[[3,4,5],[2,5,6]],[[4,7,8],[5,1,9]]])
tens_2=tf.constant([[[1,1,2],[3,9,7]],[[9,3,4],[2,3,5]]])
print(tf.linalg.cross(tens_1,tens_2))

tf.Tensor(
[[[  3  -1  -1]
  [-19   4   3]]

 [[  4  56 -51]
  [-22  -7  13]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
# Inverse of tensor : the number of rows should be equal to the number of columns
''' it's general syntax is
    tf.linalg.inv(input)
'''

tens_3=tf.constant([[1,2],[3,4]],dtype=tf.float32)
tens_3_inv=tf.linalg.inv(tens_3)
print(tens_3_inv)


print('\n\n\n')
# when you multiply a matrix with its inverse you should obatin an identity matrix
print(tens_3@tens_3_inv)

tf.Tensor(
[[-2.   1. ]
 [ 1.5 -0.5]], shape=(2, 2), dtype=float32)




tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
# Einsum method : this method performs operation according to the given input arguments and its numpy method
''' it's general syntax is
    np.einsum('ij,ij->ij,',A,B) # A and B are two metrices, ij,ij->ij is any operation (here element wise multiplication)
'''

import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[2,6,7,1],[3,9,8,1],[5,5,6,9]])

print(A.shape, B.shape)


(3, 3) (3, 4)


In [ ]:
# Now for matrix multiplication
print(np.einsum('ij,jk->ik',A,B))

# can also be done using matmal
print('\n\n\n')
print(np.matmul(A,B))

[[ 23  39  41  30]
 [ 53  99 104  63]
 [ 83 159 167  96]]




[[ 23  39  41  30]
 [ 53  99 104  63]
 [ 83 159 167  96]]


In [ ]:
# For element wise multiplication
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.einsum('ij,ij->ij',A,c))


# it can also be done simply
print('\n\n\n',A*c)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]



 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
# For matrix transpose
print(np.einsum('ij->ji',A))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [2]:
# eisnum operator is used to solve very complex operations
import numpy as np
q = np.random.randn(32,64,512)
k = np.random.randn(32,128,512)

# the b in bqm means the batch means number of matrices, q and k means rows and m means columns

print(np.einsum('bqm, bkm ->bqk',q,k).shape)

(32, 64, 128)


## Common Tensorflow functions


In [13]:
# Expand dimensions method : Returns a tensor with a length 1 axis inserted at index axis or adds extra axis to input tensor
''' it's general syntax is
    tf.expand_dims(input, axis, name=None)
'''
tens = tf.constant([[1,2,3],[4,5,6]])
print(tens)
print('\n\n\n')
print(tf.expand_dims(tens, axis=1 ))
print('\n\n\n')
print(tf.expand_dims(tens, axis=2 ))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)




tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]], shape=(2, 1, 3), dtype=int32)




tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]], shape=(2, 3, 1), dtype=int32)


In [27]:
# Squeeze Method : Removes dimensions of size 1 from shape of tensor
''' the general syntax of squeeze method is
    tf.squeeze(input, axis=None, name=None)
'''
tens=tf.constant([[[1,2,3],[4,5,6]]])
print(tens.shape)
tens_squeezed = tf.squeeze(tens, axis=0)
print(tens_squeezed.shape)

(1, 2, 3)
(2, 3)


In [34]:
# Reshape Method : it reshapes a tensor
''' the general syntax for reshape method is
    tf.reshape(tensor, shape, name=None)
'''
tens=tf.constant([[[1,2,3],[4,5,6]],[[5,2,4],[9,8,1]]])
tenso=tf.constant([[1,2,3,4],[5,6,7,8]])
reshape_tens=tf.reshape(tenso, [4,2] )
reshape_tenso=tf.reshape(tens,[4,3])
print(reshape_tens)
print('\n\n\n',reshape_tenso)

# the simple rule is that just count the number of elements and then divide according to its multiple

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)



 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [5 2 4]
 [9 8 1]], shape=(4, 3), dtype=int32)
